I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    N "What's your name again? I didn't quite catch it the first time."
  File "game/script.rpy", line 16, in callback
    elif scrollingtextevent == "slow_done" or event == "end":
NameError: global name 'event' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script
    N "What's your name again? I didn't quite catch it the first time."
  File "renpy/ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 930, in do_display
    **display_args)
  File "renpy/character.py", line 499, in display_say
    c("begin", interact=interact, type=type, **cb_args)
  File "game/script.rpy", line 16, in callback
    elif scrollingtextevent == "slow_done" or event == "end":
NameError: global name 'event' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 7.5.3.22090809
 
Thu Oct 27 00:12:22 2022
